apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
  namespace: {{ required "namespace is missing" .Values.namespace }}
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        k8s-app: {{ .Chart.Name }}
    spec:
      {{- if eq .Values.namespace "kube-system" }}
      priorityClassName: system-cluster-critical
      {{- else }}
      priorityClassName: spotinst-cluster-critical
      {{- end }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: k8s-app
                    operator: In
                    values:
                    - {{ .Chart.Name }}
                topologyKey: kubernetes.io/hostname
      containers:
      - name: {{ .Chart.Name }}
        image: spotinst/kubernetes-cluster-controller:{{ .Chart.AppVersion }}
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 4401
          initialDelaySeconds: 300
          periodSeconds: 20
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
        env:
        - name: SPOTINST_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-secret
              key: token
        - name: SPOTINST_ACCOUNT
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: spotinst.account
        - name: CLUSTER_IDENTIFIER
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: spotinst.cluster-identifier
        - name: BASE_SPOTINST_URL
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: base-url
              optional: true
        - name: PROXY_URL
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: proxy-url
              optional: true
        - name: DISABLE_AUTO_UPDATE
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: disable-auto-update
              optional: true
        - name: ENABLE_CSR_APPROVAL
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: enable-csr-approval
              optional: true
        - name: POD_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      serviceAccountName: {{ .Chart.Name }}
      tolerations:
      - key: node.kubernetes.io/not-ready
        effect: NoExecute
        operator: Exists
        tolerationSeconds: 150
      - key: node.kubernetes.io/unreachable
        effect: NoExecute
        operator: Exists
        tolerationSeconds: 150
      - key: node-role.kubernetes.io/master
        operator: Exists
